pipeline
        {
            parameters
            {
                // Define DRIVER parameter for running the test
                choice(name: 'DRIVER', description: 'Choose browser', choices: 'chrome\nfirefox\nheadless')

                // Define test path to run
                string(name: 'TESTS_TO_RUN', defaultValue: 'tests/test_purchase_tickets.py', description: 'choose test to run')
            }

            options
            {
                // keep 100 last builds
                buildDiscarder(logRotator(numToKeepStr: '100'))

                // add timestamp
                timestamps()
            }
            agent any // run the
            stages
            {
                stage('SCM: code update')
                {
                    steps
                    {
                        // checking out repository
                        checkout([
                                $class: 'GitSCM', branches: [[name: 'master']],
                                userRemoteConfigs: [[url: 'https://github.com/eliranshani/selenium-docker-allure.git']]
                        ])

                        // Create Allure report folders and grant relevant permissions
                        sh "mkdir -p ./blazedemo_app/allure-results"
                        sh "rm -rf ./blazedemo_app/allure-results/*"
                        sh "chown jenkins:jenkins ./blazedemo_app/allure-results"
                    }
                }
                stage('Docker build')
                {
                    steps
                    {
                        script
                        {
                            sh "cp selenium-base-image/Dockerfile ."
                            docker.build("blazemeter/selenium_base")
                            sh "cp selenium-automation-run/Dockerfile ."
                            docker.build("blazemeter/selenium_image")
                        }
                    }
                }
                stage('Run test')
                {
                    steps
                    {
                        script
                        {
                            try
                            {
                                def now = new Date()
                                tstamp = now.format("yyyyMMdd-HH:mm:ss.SSSS", TimeZone.getTimeZone('UTC'))

                                sh "docker run " +
                                        "--privileged " +
                                        "--shm-size=1g " +                                                                  // shared memory size is set to 1G to prevent chromedriver memory leak
                                        "--rm " +                                                                           // remove container at the end of the session
                                        "-e PYTHONPATH=/code/ " +                                                           // environment variable support
                                        "-w=/code " +                                                                       // setting working directory
                                        "-v `pwd`/blazedemo_app:/code " +                                                   // mount git repository to the container
                                        "blazemeter/selenium_image:latest " +                                               // the specific image that being used (latest image by default)
                                        "-v"                                                                                // verbose (for debugging purpose)
                            }
                            catch (error)
                            {
                                echo error.message
                            }
                        }
                    }
                }
            }
            post
            {
                always
                {
                    // Generate Allure Report
                    generateAllureReport()

                    // Send Slack notification
                    sendSlackNotification()
                }
            }
        }

// Generate Allure report function
def generateAllureReport()
    {
        try
        {
            allure([
                    commandline      : '2.5.0',
                    includeProperties: false,
                    jdk              : '',
                    properties       : [[key: 'allure.tests.management.pattern', value: 'http://tms.company.com/%s']],
                    reportBuildPolicy: 'ALWAYS',
                    results          : [[path: 'blazedemo_app/allure-results']]
            ])
        }
        catch (error)
        {
            error.message
        }
    }

// Send Slack notification function
def sendSlackNotification(String buildStatus = 'STARTED')
    {
        // build status of null means successful
        buildStatus =  buildStatus ?: 'SUCCESSFUL'

        // Default values
        def colorName = 'RED'
        def colorCode = '#FF0000'
        def subject = "${buildStatus}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'"
        def summary = "${subject} (${env.BUILD_URL})"

        // Override default values based on build status
        if (buildStatus == 'STARTED') {
            color = 'YELLOW'
            colorCode = '#FFFF00'
        } else if (buildStatus == 'SUCCESSFUL') {
            color = 'GREEN'
            colorCode = '#00FF00'
        } else {
            color = 'RED'
            colorCode = '#FF0000'
        }

        // Send notifications
//        slackSend (color: colorCode, message: summary)
        channel = "jenkins_notifications"
        slackSend (color: colorCode, message: summary, channel: "#${channel}")
    }